apiVersion: v1
kind: Pod
metadata:
  name: konnekta-4-1-3sh4i
  generateName: konnekta-4-1-
  namespace: konn
  selfLink: /api/v1/namespaces/konn/pods/konnekta-4-1-3sh4i
  uid: cad8482c-619a-11e7-8417-525400c583ad
  resourceVersion: '16586'
  creationTimestamp: '2017-07-05T15:58:31Z'
  labels:
    app: konnekta-4
    deployment: konnekta-4-1
    deploymentconfig: konnekta-4
  annotations:
    kubernetes.io/created-by: "{\"kind\":\"SerializedReference\",\"apiVersion\":\"v1\",\"reference\":{\"kind\":\"ReplicationController\",\"namespace\":\"konnekt\",\"name\":\"konnekta-4-1\",\"uid\":\"c7e8df0c-619a-11e7-8417-525400c583ad\",\"apiVersion\":\"v1\",\"resourceVersion\":\"16572\"}}\n"
    openshift.io/deployment-config.latest-version: '1'
    openshift.io/deployment-config.name: konnekta-4
    openshift.io/deployment.name: konnekta-4-1
    openshift.io/generated-by: OpenShiftNewApp
    openshift.io/scc: anyuid
spec:
  volumes:
    -
      name: konnekta-4-volume-1
      emptyDir:
    -
      name: konnekta-4-volume-2
      emptyDir:
    -
      name: konnekta-4-volume-3
      emptyDir:
    -
      name: konnekta-4-volume-4
      emptyDir:
    -
      name: default-token-qloc7
      secret:
        secretName: default-token-qloc7
  containers:
    -
      name: konnekta-4
      image: 'confluentinc/cp-kafka-connect@sha256:1211e0135cb01a609ff86300d4dea4cd2d1171c9195fa16ee89b9c37480ca764'
      ports:
        -
          containerPort: 8083
          protocol: TCP
        -
          containerPort: 9092
          protocol: TCP
      env:
        -
          name: CONNECT_BOOTSTRAP_SERVERS
          value: '192.168.112.163:9092'
        -
          name: CONNECT_CONFIG_STORAGE_TOPIC
          value: danila-connect-configs-f
        -
          name: CONNECT_GROUP_ID
          value: connect_group_multi_worker_8
        -
          name: CONNECT_INTERNAL_KEY_CONVERTER
          value: org.apache.kafka.connect.json.JsonConverter
        -
          name: CONNECT_INTERNAL_KEY_CONVERTER_SCHEMAS_ENABLE
          value: 'false'
        -
          name: CONNECT_INTERNAL_VALUE_CONVERTER
          value: org.apache.kafka.connect.json.JsonConverter
        -
          name: CONNECT_INTERNAL_VALUE_CONVERTER_SCHEMAS_ENABLE
          value: 'false'
        -
          name: CONNECT_KEY_CONVERTER
          value: org.apache.kafka.connect.storage.StringConverter
        -
          name: CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE
          value: 'false'
        -
          name: CONNECT_OFFSET_STORAGE_TOPIC
          value: danila-connect-offsets-f
        -
          name: CONNECT_REST_ADVERTISED_HOST_NAME
          value: connect22
        -
          name: CONNECT_STATUS_STORAGE_TOPIC
          value: danila-connect-status-f
        -
          name: CONNECT_VALUES_CONVERTER_SCHEMAS_ENABLE
          value: 'false'
        -
          name: CONNECT_VALUE_CONVERTER
          value: org.apache.kafka.connect.storage.StringConverter
        -
          name: HADOOP_USER_NAME
          value: hdfs
        -
          name: TERM
          value: xterm
      resources:
      Limits:
          cpu:  200m
          memory: 400Mi
      volumeMounts:
        -
          name: konnekta-4-volume-1
          mountPath: /etc/kafka-connect/secrets
        -
          name: konnekta-4-volume-2
          mountPath: /etc/kafka/secrets
        -
          name: konnekta-4-volume-3
          mountPath: /var/lib/kafka/data
        -
          name: konnekta-4-volume-4
          mountPath: /etc/kafka-connect/jars
        -
          name: default-token-qloc7
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePath: /dev/termination-log
      imagePullPolicy: Always
      securityContext:
        capabilities:
          drop:
            - MKNOD
            - SYS_CHROOT
        privileged: false
        seLinuxOptions:
          level: 's0:c7,c4'
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  host: origin
  serviceAccountName: default
  serviceAccount: default
  nodeName: origin
  securityContext:
    seLinuxOptions:
      level: 's0:c7,c4'
  imagePullSecrets:
    -
      name: default-dockercfg-zzlyf
status:
  phase: Running
  conditions:
    -
      type: Initialized
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2017-07-05T15:58:31Z'
    -
      type: Ready
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2017-07-05T15:58:34Z'
    -
      type: PodScheduled
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2017-07-05T15:58:31Z'
  hostIP: 10.0.2.15
  podIP: 172.17.0.9
  startTime: '2017-07-05T15:58:31Z'
  containerStatuses:
    -
      name: konnekta-4
      state:
        running:
          startedAt: '2017-07-05T15:58:34Z'
      lastState:
      ready: true
      restartCount: 0
      image: 'confluentinc/cp-kafka-connect@sha256:1211e0135cb01a609ff86300d4dea4cd2d1171c9195fa16ee89b9c37480ca764'
      imageID: 'docker://sha256:6f4b912ff3c6761b261c15f558de28c7fbc26b06731cbff9fc543a9ede54e5b3'
      containerID: 'docker://256c35fc139f8c2a76699d773c09410d1514b0b35d65e903f2008bdb4b93716f'
