apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "core-resource-limits-4" 
spec:
  limits:
    - type: "Pod"
      max:
        cpu: "2" 
        memory: "1Gi" 
      min:
        cpu: "200m" 
        memory: "6Mi" 
