apiVersion: v1
kind: LimitRange
metadata:
        name: defaults-demo
spec:
  limits:
  - default:
      cpu: 50m
      memory: 1000Mi
    defaultRequest:
      cpu: 50m
      memory: 1000Mi
    type: Container
